name: gxq_project
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.2+3
  flutter_qrscaner: ^0.0.4
  banner_view: "^1.1.2"
  shared_preferences: ^0.4.3
  video_player: ^0.10.5+2
  orientation: ^1.1.0
  seekbar: 0.0.2
  popup_window: ^1.0.0+3
#  三方登录
  sharesdk_plugin: ^1.2.4
  #阿里推送
  rammus: ^0.0.3
  #蓝牙
  flutter_blue: ^0.7.2
  dio: 3.0.9
  json_annotation: ^3.0.1
  date_format: ^1.0.6
  event_bus: ^1.1.0
  sqflite: ^1.1.3
  uuid: 2.0.4
  loading_dialog: ^0.0.1+1
  common_utils: ^1.2.1
  url_launcher: ^5.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  json_serializable: ^3.2.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/ali_connors.png
    - assets/images/ali_connors_sml.png
    - assets/images/qrcode.png
    - assets/images/icon_wan_android.png
    - assets/images/ic_launcher_news.png
    - assets/images/guide1.png
    - assets/images/guide2.png
    - assets/images/guide3.png
    - assets/images/guide4.png
    - assets/images/splash_bg.png
    - assets/images/ic_avatar.png
    - assets/images/ic_arraw.png
    - assets/images/ic_back.png
    - assets/images/ic_saoyisao.png
    - assets/images/ic_setting.png
    - assets/images/ic_wenduji.png
    - assets/images/ic_arraw_down.png
    - assets/images/ic_help.png
    - assets/images/ic_wendu_down.png
    - assets/images/ic_wendu_up.png
    - assets/images/ic_add.png
    - assets/images/ic_is_select.png
    - assets/images/ic_no_select.png
    - assets/images/ic_device_manage_empty.png
    - assets/images/ic_image_1.png
    - assets/images/ic_image_2.png
    - assets/images/ic_about.png
    - assets/video.mp4
    - assets/images/ic_play_ling.png
    - assets/images/ic_play_no.png
    - assets/images/ic_back_white.png
    - assets/images/ic_login_bg.png
    - assets/images/ic_push_dialog_bg.png





